export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UPLOAD_CONTACT_LIST = "UPLOAD_CONTACT_LIST";
export const FILTER_CONTACTS = "FILTER_CONTACTS";

export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const ERROR_POST_REQUEST = "ERROR_POST_REQUEST";
export const ERROR_DELETE_REQUEST = "ERROR_DELETE_REQUEST";
export const ERROR_RESET = "ERROR_RESET";
